export const commentsData = [
  {
    author: "Kunto",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    date: "Today at 3:00PM",
    text: "Nice Info!",
  },
  {
    author: "Dida",
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    date: "Today at 5:00PM",
    text: "What a Story!",
  },
  {
    author: "Asep",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    date: "Today at 8:00PM",
    text: "WOW!",
  },
  {
    author: "Rina",
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
    date: "Today at 1:30PM",
    text: "Thanks for sharing!",
  },
  {
    author: "Budi",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
    date: "Yesterday at 2:15PM",
    text: "This is really helpful.",
  },
  {
    author: "Lina",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    date: "Yesterday at 11:00AM",
    text: "Great insights!",
  },
  {
    author: "Farhan",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    date: "5 days ago",
    text: "I learned a lot from this.",
  },
  {
    author: "Dewi",
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    date: "5 days ago",
    text: "Fantastic explanation!",
  },
  {
    author: "Rizky",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    date: "3 days ago",
    text: "Really good content!",
  },
  {
    author: "Putri",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    date: "3 days ago",
    text: "I appreciate this!",
  },
  {
    author: "Eka",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    date: "1 week ago",
    text: "Interesting perspective.",
  },
  {
    author: "Tina",
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
    date: "1 week ago",
    text: "Well written!",
  },
  {
    author: "Yusuf",
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
    date: "2 weeks ago",
    text: "Awesome work!",
  },
  {
    author: "Fauzi",
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
    date: "2 weeks ago",
    text: "Keep it up!",
  },
  {
    author: "Anisa",
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
    date: "3 weeks ago",
    text: "I found this very engaging.",
  },
  {
    author: "Rudi",
    avatar: "https://randomuser.me/api/portraits/men/10.jpg",
    date: "3 weeks ago",
    text: "Exactly what I needed!",
  },
  {
    author: "Bella",
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
    date: "1 month ago",
    text: "Helpful information!",
  },
  {
    author: "Luki",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    date: "1 month ago",
    text: "Nice read!",
  },
  {
    author: "Dina",
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
    date: "1 month ago",
    text: "Very insightful.",
  },
  {
    author: "Sari",
    avatar: "https://randomuser.me/api/portraits/women/9.jpg",
    date: "1 month ago",
    text: "Thanks for this post!",
  },
  {
    author: "Rudi",
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
    date: "2 months ago",
    text: "Great job!",
  },
];
